### ISSUE TITLE
Convert HTML Hex Color to RGB Color and viceversa does not work.

### ISSUE THREAD

**Issue by Hyde1942** [akalongman/sublimetext-stringutilities#10]
Im testing the plugin and above function does not seem to work. I tried to convert the following hex colors to RGB:
```
#FFF
#fff
#FFFFFF
#ffffff

```

It did not work, I also tried to convert RGB to HEX like for example:
```
rgb(0,2,33);
```
Did not work either.

Im getting the following errors in the console

```

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/Hyde1942/Library/Application Support/Sublime Text 3/Packages/StringUtilities/stringutilities.py", line 188, in run
    self.view.replace(edit, region, self.hex_to_rgb(text))
  File "/Users/Hyde1942/Library/Application Support/Sublime Text 3/Packages/StringUtilities/stringutilities.py", line 197, in hex_to_rgb
    value = value.lstrip('#')
TypeError: Type str doesn't support the buffer API
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/Hyde1942/Library/Application Support/Sublime Text 3/Packages/StringUtilities/stringutilities.py", line 217, in run
    rgb_match = re.match(reg_rgb, text)
  File "./re.py", line 156, in match
TypeError: can't use a string pattern on a bytes-like object

```

<img width="1001" alt="screen shot 2015-10-08 at 7 13 57 pm" src="https://cloud.githubusercontent.com/assets/6386085/10383805/ce252d62-6df0-11e5-86b6-203bc1369f2e.png">

**Comment by akalongman** [comment]
Fixed in 1.4.0
