### ISSUE TITLE
global name 'unichr' is not defined

### ISSUE THREAD

**Issue by stranbird** [akalongman/sublimetext-stringutilities#6]
Hi, I got the following error when trying to convert a string into its unicode representation, any idea?

Thanks!

```
NameError: global name 'unichr' is not defined
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/yuanfei/Library/Application Support/Sublime Text 3/Packages/StringUtilities/stringutilities.py", line 110, in run
    text = re.sub(pattern, lambda m: unichr(int(m.group(2), 16)), self.view.substr(region))
  File "./re.py", line 170, in sub
  File "/Users/yuanfei/Library/Application Support/Sublime Text 3/Packages/StringUtilities/stringutilities.py", line 110, in <lambda>
    text = re.sub(pattern, lambda m: unichr(int(m.group(2), 16)), self.view.substr(region))
```

**Comment by chence** [comment]
+1 same error

**Comment by Vasfed** [comment]
`unichr` was removed from python3 because regular `chr` now does the same
Created a PR #9
